/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        bg:      '#0C0C0C',
        surface: '#111111',
        'surface-2': '#181818',
        'surface-3': '#1F1F1F',
        border:  'rgba(255,255,255,0.07)',
        'border-strong': 'rgba(255,255,255,0.12)',
        muted:   '#6B7280',
        dim:     '#374151',
        yellow:  '#F5C518',
        'yellow-dim': 'rgba(245,197,24,0.12)',
        purple:  '#7C3AED',
        'purple-dim': 'rgba(124,58,237,0.12)',
        white:   '#FAFAFA',
        text:    '#E5E5E5',
        'text-2':'#9CA3AF',
      },
      fontFamily: {
        sans:    ['"Inter"', 'system-ui', 'sans-serif'],
        display: ['"Inter"', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '1.2', letterSpacing: '0.08em' }],
        'xs':  ['12px', { lineHeight: '1.4' }],
        'sm':  ['13px', { lineHeight: '1.5' }],
        'base':['14px', { lineHeight: '1.6' }],
        'md':  ['15px', { lineHeight: '1.5' }],
        'lg':  ['18px', { lineHeight: '1.4', letterSpacing: '-0.01em' }],
        'xl':  ['22px', { lineHeight: '1.3', letterSpacing: '-0.02em' }],
        '2xl': ['28px', { lineHeight: '1.2', letterSpacing: '-0.03em' }],
        '3xl': ['36px', { lineHeight: '1.1', letterSpacing: '-0.04em' }],
      },
      fontWeight: {
        normal: 400,
        medium: 500,
        semibold: 600,
        bold:   700,
        black:  900,
      },
      animation: {
        'fade-in':   'fadeIn 0.3s ease forwards',
        'slide-up':  'slideUp 0.3s cubic-bezier(0.16,1,0.3,1) forwards',
        'spin-slow': 'spin 1.5s linear infinite',
        'shimmer':   'shimmer 1.8s infinite',
        'pulse-dot': 'pulseDot 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:   { from: { opacity: 0 },                      to: { opacity: 1 } },
        slideUp:  { from: { opacity: 0, transform: 'translateY(12px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        shimmer:  { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        pulseDot: { '0%,100%': { opacity: 1 }, '50%': { opacity: 0.3 } },
      },
    },
  },
  plugins: [],
};
